// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3HncCo3_i1JsGGdFt5KDHxW1MaZ6bo5w',
    appId: '1:205022775029:web:cd97ef625c4f321555a7bc',
    messagingSenderId: '205022775029',
    projectId: 'komunoto-app',
    authDomain: 'komunoto-app.firebaseapp.com',
    storageBucket: 'komunoto-app.appspot.com',
    measurementId: 'G-CVJFN01JCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJL6wZcq4ZOzzU_MKzaBhBT8YukWWzxio',
    appId: '1:205022775029:android:bf5454f5e18a7e3055a7bc',
    messagingSenderId: '205022775029',
    projectId: 'komunoto-app',
    storageBucket: 'komunoto-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0CrIMG1tav8GsoRW4lIqYYdKPUhWksnY',
    appId: '1:205022775029:ios:0528d14d4877859255a7bc',
    messagingSenderId: '205022775029',
    projectId: 'komunoto-app',
    storageBucket: 'komunoto-app.appspot.com',
    iosBundleId: 'com.example.otoApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0CrIMG1tav8GsoRW4lIqYYdKPUhWksnY',
    appId: '1:205022775029:ios:0528d14d4877859255a7bc',
    messagingSenderId: '205022775029',
    projectId: 'komunoto-app',
    storageBucket: 'komunoto-app.appspot.com',
    iosBundleId: 'com.example.otoApps',
  );
}
